# Generated by Django 3.1.6 on 2021-02-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image', models.URLField()),
                ('genre', models.CharField(choices=[('ACTION', 'Action'), ('DRAMA', 'Drama'), ('HOROR', 'Horor'), ('ROMANCE', 'Romance'), ('COMEDY', 'Comedy'), ('THRILLER', 'Thriller'), ('CRIME', 'Crime'), ('WESTERN', 'Western')], default='ACTION', max_length=32)),
            ],
        ),
    ]
