# Generated by Django 3.1.6 on 2021-03-04 12:49

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210303_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=movies.models.upload_to, verbose_name='Image'),
        ),
    ]
