# Generated by Django 3.1.6 on 2021-03-05 13:58

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20210304_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=movies.models.upload_to),
        ),
    ]
