# Generated by Django 3.1.6 on 2021-03-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
        migrations.AlterField(
            model_name='movie',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
