# Generated by Django 3.1.6 on 2021-03-08 09:57

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20210305_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image2',
        ),
        migrations.AddField(
            model_name='movie',
            name='thumbnail_photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='photos'),
        ),
    ]
